-- =============================================================================
-- Public Outreach — PAP Territory Management
-- Migration 005: per-supervisor zone assignment + multiple zones per supervisor
-- =============================================================================
-- Run this in Supabase Dashboard → SQL Editor → New query → Run

-- ---------------------------------------------------------------------------
-- 1. Add supervisor_id to daily_zones
--    Drop the old UNIQUE(team_id, date) constraint — allow multiple zones
--    per team per day (one per supervisor, or multiple for the same supervisor)
-- ---------------------------------------------------------------------------
ALTER TABLE public.daily_zones
  ADD COLUMN IF NOT EXISTS supervisor_id uuid REFERENCES public.users(id);

-- Drop old unique constraint (name generated by Postgres from the UNIQUE clause)
ALTER TABLE public.daily_zones
  DROP CONSTRAINT IF EXISTS daily_zones_team_id_date_key;

CREATE INDEX IF NOT EXISTS idx_daily_zones_supervisor_id
  ON public.daily_zones(supervisor_id);

COMMENT ON COLUMN public.daily_zones.supervisor_id IS
  'The specific supervisor this zone is assigned to (nullable for legacy rows)';

-- ---------------------------------------------------------------------------
-- 2. Add supervisor_id to daily_entries (track which supervisor submitted)
--    Drop old UNIQUE(team_id, entry_date) partial index.
--    New constraint: one EOD per supervisor per day.
-- ---------------------------------------------------------------------------
ALTER TABLE public.daily_entries
  ADD COLUMN IF NOT EXISTS supervisor_id uuid REFERENCES public.users(id);

-- Drop old index (allows us to recreate with supervisor scope)
DROP INDEX IF EXISTS idx_daily_entries_team_date;

-- One EOD per supervisor per day
CREATE UNIQUE INDEX IF NOT EXISTS idx_daily_entries_supervisor_date
  ON public.daily_entries(supervisor_id, entry_date)
  WHERE supervisor_id IS NOT NULL AND entry_date IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_daily_entries_supervisor_id
  ON public.daily_entries(supervisor_id);

COMMENT ON COLUMN public.daily_entries.supervisor_id IS
  'The supervisor who submitted this EOD';

-- ---------------------------------------------------------------------------
-- 3. RLS update for daily_zones
--    Supervisors can now see their own assigned zones PLUS other zones
--    from the same team (for map context).
--    Keep managers/admins with full write access.
-- ---------------------------------------------------------------------------

-- Drop overly broad read policy and replace with role-aware one
DROP POLICY IF EXISTS "daily_zones: authenticated can read" ON public.daily_zones;

CREATE POLICY "daily_zones: authenticated can read"
  ON public.daily_zones FOR SELECT TO authenticated USING (true);

-- (Insert/update/delete policies are unchanged — managers and admins only)

-- ---------------------------------------------------------------------------
-- 4. RLS update for daily_entries
--    Supervisors can only insert/update their own entries.
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS "daily_entries: supervisors can insert" ON public.daily_entries;

CREATE POLICY "daily_entries: supervisors can insert"
  ON public.daily_entries FOR INSERT TO authenticated
  WITH CHECK (
    public.get_my_role() IN ('admin', 'territory_manager')
    OR (
      public.get_my_role() = 'supervisor'
      AND supervisor_id = auth.uid()
    )
  );
